project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "slides/slides.qmd"

website:
  title: "Git and GitHub for health data science"
  navbar:
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: setup.qmd
        text: Setup
      - href: exercises.qmd
        text: Exercises
      - href: slides/slides.html
        text: Slides
    right:
      - text: "ASMHI MSc"
        href: index.qmd
  page-footer:
    left: "ASMHI MSc · King's College London · 20 April 2026"

format:
  html:
    theme: [cosmo, website.scss]
    toc: true
    code-copy: true
